version: '3.8'
services:
  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_TCP_PORT=1113  
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-volume-data:

